### ISSUE TITLE
Downloading multiple files based on LIST

### ISSUE THREAD

**Issue by evdheuvel70** [anversoft/node-red-contrib-advanced-ftp#4]
Hi,

I'm creating a flow where I need to download one or more files based on the information returned by LIST. For this I've added a split node and planned to use GET to download the individual files. For some reason it downloads only the first file from the list. When I debug msg.filename before the GET node the paths of the various files are shown as expected. Adding a debug node after the GET it shows the name of the first file for each file in the list. 

What would be the best approach to download multiple files?

Hope you can assist,

Erik

![ftp-download-multiple-files](https://user-images.githubusercontent.com/55614879/99529266-cc5b3380-299f-11eb-8641-dedd9a147a73.png)

**Comment by anversoft** [comment]
Hi Erik,

currently the client doesn't have an internal buffer, so if more files are requested from it in a very short period of time the function is recreated with the first message because the file download has not yet been completed.

Here, I created a small buffer that waits for a file to download before sending a new one. You can add as many to the queue as you want. Also add all protections to avoid unexpected loops or false downloads.

If you plan to download large files, increase the Watchdog node time to prevent the queue from resuming.

I hope I have been helpful,

Andrea Verardi

CODE:
`[{"id":"ca3a1161.b5a26","type":"inject","z":"be397ec1.70dd","name":"Request","topic":"Request","payload":"{\"filename\":\"Test.txt\",\"localFilename\":\"localText.txt\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":228.5,"y":246,"wires":[["ad277ad4.3479d8"]]},{"id":"2322bbc5.55c6c4","type":"function","z":"be397ec1.70dd","name":"FTP Buffer","func":"var contextName = \"file_buffer\";                                                //Context Buffer Name\nvar fb = context.get(contextName) || [];                                        //Get the context files names array, if it doesn't exist, create it.\n\nif(msg.topic === \"Flush\"){                                                      //Flush Requested, recreate the buffer\n    fb = [];\n    context.set(contextName, fb);\n    return null;\n}\n\nif(!msg.hasOwnProperty(\"filename\") || !msg.hasOwnProperty(\"localFilename\")){    //Check if msg contains the ftp properties.  \n    node.warn(\"msg does not contain filename or localFilename property\");\n    return null;    \n}\n\nvar ftpMessage = {                                                              //Create the ftp msg object\n    filename : msg.filename,\n    localFilename : msg.localFilename,\n}\n\nif(msg.topic === \"Request\"){                                                    //Request Command, add the new request to the buffer\n    \n    let firstRequest = fb.length > 0 ? false : true;                            //If the buffer is empty, send the first element of the array\n    fb.push(ftpMessage);\n    \n    if(firstRequest){\n        ftpMessage = fb[0];\n        node.send(ftpMessage);\n    }\n}\n\nif(msg.topic === \"Completed\" && fb.length > 0){                                 //Completed Command, a file download is complete\n\n    let index = -1;\n    \n    for(let file in fb){\n\n        if(fb[file].filename == ftpMessage.filename && \n           fb[file].localFilename == ftpMessage.localFilename){\n               \n            index = file;\n            break;\n        }\n    }\n    \n    if (index > -1) {                                                           //If the index is found, remove the request from the buffer\n        fb.splice(index, 1);\n    }\n    \n    if(fb.length > 0){                                                          //Send the fist element of the array\n        ftpMessage = fb[0];\n        node.send(ftpMessage);\n    }\n}\n\ncontext.set(contextName, fb);                                                   //Update the buffer\n\n","outputs":1,"noerr":0,"x":634,"y":246,"wires":[["101be173.a0321f","802aac54.e48d9","17fdd538.b72f2b"]]},{"id":"ad277ad4.3479d8","type":"function","z":"be397ec1.70dd","name":"Dummy Request","func":"var ftpMessage = {\n    topic : msg.topic,\n    filename : msg.payload.filename,\n    localFilename : msg.payload.localFilename,\n}\n\nreturn ftpMessage;","outputs":1,"noerr":0,"x":417,"y":246,"wires":[["2322bbc5.55c6c4"]]},{"id":"8c84c47c.a92c38","type":"inject","z":"be397ec1.70dd","name":"Manual Flush","topic":"Flush","payload":"a","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":237,"y":295,"wires":[["2322bbc5.55c6c4"]]},{"id":"101be173.a0321f","type":"delay","z":"be397ec1.70dd","name":"Fake GET Node","pauseType":"delay","timeout":"4","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":837,"y":247,"wires":[["7bfa3a61.e19ce4"]]},{"id":"7bfa3a61.e19ce4","type":"change","z":"be397ec1.70dd","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"Completed","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1055,"y":246,"wires":[["4bacc921.bdb528","c3ed89ed.a75388"]]},{"id":"4bacc921.bdb528","type":"debug","z":"be397ec1.70dd","name":"Download Completed","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1266.5,"y":205,"wires":[]},{"id":"c3ed89ed.a75388","type":"link out","z":"be397ec1.70dd","name":"","links":["ceb7cbdd.3b5618"],"x":1181,"y":245,"wires":[]},{"id":"ceb7cbdd.3b5618","type":"link in","z":"be397ec1.70dd","name":"","links":["c3ed89ed.a75388","7d2196e1.5d0f98"],"x":546,"y":176,"wires":[["2322bbc5.55c6c4"]]},{"id":"802aac54.e48d9","type":"debug","z":"be397ec1.70dd","name":"To GET node","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":827,"y":197,"wires":[]},{"id":"17fdd538.b72f2b","type":"trigger","z":"be397ec1.70dd","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"5","extend":true,"units":"s","reset":"","bytopic":"all","name":"Watchdog","x":625,"y":297,"wires":[["a7df59c7.b1ffb8"]]},{"id":"a7df59c7.b1ffb8","type":"change","z":"be397ec1.70dd","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"Flush","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":635,"y":345,"wires":[["7d2196e1.5d0f98","4721f7cb.0a2fe8"]]},{"id":"7d2196e1.5d0f98","type":"link out","z":"be397ec1.70dd","name":"","links":["ceb7cbdd.3b5618"],"x":747,"y":345,"wires":[]},{"id":"4721f7cb.0a2fe8","type":"debug","z":"be397ec1.70dd","name":"Flush if the Completed msg doesn't arrive","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":727,"y":387,"wires":[]}]`

**Comment by evdheuvel70** [comment]
Excellent, got it working! Thanks for your quick reply, much appreciated.
